project_id = "kcxhrcquzsqyydoplmdt"

[functions.farmacia-stats]
verify_jwt = false

[functions.list-users]
verify_jwt = false

[functions.create-farmacia-user]
verify_jwt = false

[functions.send-stock-alert]
verify_jwt = false
